### ISSUE TITLE
extend to video

### ISSUE THREAD

**Issue by robbiedood** [AguilarLagunasArturo/pexels-api#1]
Dear AguilarLagunasArturo,

It's great to find your pexels api in python. So far it works nice with getting photos from pexels.
We were wondering if you have a plan to extend the api to include searching and download video.

Thanks!

**Comment by lukelu520** [comment]
> Dear AguilarLagunasArturo,
> 
> It's great to find your pexels api in python. So far it works nice with getting photos from pexels.
> We were wondering if you have a plan to extend the api to include searching and download video.
> 
> Thanks!

Never mind, I've made a simple extension. Maybe I could git it for your review.
